### ISSUE TITLE
Graph UI/UX updates

### ISSUE THREAD

**Issue by charlotte-chiang** [anytypeio/roadmap#18]
**High level:**
Improve graph UI & functionality

**Related Threads & Feature Requests**
https://community.anytype.io/t/ability-to-filter-the-graph-in-graph-view/5898
https://community.anytype.io/t/in-the-graph-view-be-able-to-filter-search-by-object-type-and-or-relation/6618
https://community.anytype.io/t/ability-to-group-sort-and-filter-links-in-navigation-pane/7590
https://community.anytype.io/t/some-suggestions-for-the-graph-view-feature/4706
https://community.anytype.io/t/implementing-a-local-graph-view/7615

**Comment by GpL-inc** [comment]
.
