### ISSUE TITLE
Toggle not opening when pdf exported

### ISSUE THREAD

**Issue by diogocardoso28** [anytypeio/roadmap#31]
If I have toggles on my document they export as is, if they are closed they will be exported closed. Since this behaviour might be wanted by some, a toggle as an export setting would be nice.

Expected:
![image](https://github.com/anyproto/roadmap/assets/65686179/ed922512-7be2-4498-8c29-bf40fd704043)

Actual result:
![image](https://github.com/anyproto/roadmap/assets/65686179/1f4da6a8-e3ba-423f-9e7f-efe9920580c2)

**Comment by fuksman** [comment]
Hi @diogocardoso28, thank you for your suggestion. We'll take it into account when planning our roadmap.

We're also planning to release an API later this year. This will enable developers to create custom importers and exporters. It's possible that "advanced PDF export" could be one of these integrations.

We only keep planned roadmap items in this repo. Please consider submitting feature requests to https://community.anytype.io. Here is a request similar to yours: https://community.anytype.io/t/expand-all-toggle-blocks-when-exporting-to-pdf/8470
I will remove this issue, as it's not a part of roadmap yet.
