### ISSUE TITLE
Support Mermaid code

### ISSUE THREAD

**Issue by atom-tr** [anytypeio/roadmap#32]
Support render mermaid code in code block like Notion or Github Markdown
Library: https://mermaid.js.org/

**Comment by fuksman** [comment]
Hi @atom-tr, thank you for your suggestion. We'll take it into account when planning our roadmap.

We only keep planned roadmap items in this repo. Please consider submitting feature requests to https://community.anytype.io/. Here is a request similar to yours: https://community.anytype.io/t/ability-to-add-diagrams-diagram-editor/1561
I am closing this issue, as it's not a part of roadmap yet.
