### ISSUE TITLE
Backlinks MVP

### ISSUE THREAD

**Issue by ignatovv** [anytypeio/roadmap#36]
Add and ability to see backlinks (list of objects with link to the current object) in object relations menu

**Comment by Olanrelekan96** [comment]
Yes! Huge development for core PKM'ers

**Comment by rolling-st0ne** [comment]
It would also be great if backlinks were grouped by type of objects that refer to to current object, not displayed just like list.

**Comment by zxhd863943427** [comment]
I want to be close to the anti-chain display at the level of roamresearch, rather than just showing the title of the document.
