### ISSUE TITLE
File as an Object [part1]

### ISSUE THREAD

**Issue by charlotte-chiang** [anytypeio/roadmap#40]

**Comment by ubrandes** [comment]
Not sure if this is the intended way to contribute here, but I presume this feature is meant to support the [excellent ongoing efforts to help users migrate from Evernote](https://community.anytype.io/t/a-tool-to-import-evernote-notes-to-anytype/11483)? This would be brilliant.

**Comment by fuksman** [comment]
Hey @ubrandes, yes, this should help with the file import/export bug that is blocking the development of proper data converters (like Evernote -> Anytype).

**Comment by ubrandes** [comment]
brilliant, thank you. 13k notes are in the queue to be imported from Evernote to Anytype 🤩

**Comment by Nevarro** [comment]
Is this in any way linked to being able to open a file, edit it and save it so that changes are available on the next opening of the file? (see [here](https://community.anytype.io/t/open-and-modify-attached-files-directly-instead-of-downloading-them/1003/27?u=nevarro))

**Comment by fuksman** [comment]
hey @Nevarro, no, this issue is not connected to the in-app file editing
