### ISSUE TITLE
Featured Relations UX Improvements

### ISSUE THREAD

**Issue by charlotte-chiang** [anytypeio/roadmap#43]

**Comment by ubrandes** [comment]
Dear team, here's a [mockup of a new FR](https://community.anytype.io/t/document-view-to-show-full-size-objects-in-sets-and-collections/13506/3) to render all listed objects of a Set or Collection in full size, one after the other.

Is something like this on your roadmap for "Relations UX Improvements"?

Basically, the suggestion is to **enhance Anytype's current view layouts for sets and collections**. This makes a list of Objects readable as one document (for diaries, logs, journals, tasks, collections, travel destinations, ...). At the same time, it addresses many user needs behind transclusion and block-as-object, without changing the functionality of blocks and objects.

See attached mockup screenshot: 
(1) current List view for Sets and Collections;
(2) proposed new "Document" view layout 

![Image](https://github.com/anyproto/roadmap/assets/59647284/5c02c5cc-bb24-40b3-b544-6acdfe24d499)

**Comment by Meyu-Sys** [comment]
What are the plans for ux improvements for relations.The current flow for relations is keeping me away from anytype. It is far to convoluted and lacks important types. An easy fix would be to remove the relation library altogether.

**Comment by mifraburneo** [comment]
Although I’m not sure if this is UX related per se… Will having bidirectional relations be a part of this? And some sort of Rollups? This is the only thing keeping me away from Anytype 🥲
I LOVE the fact that everything is object based and that I can create tasks anywhere but… if I create a task inside another object, that object should also be an automatic relation with the task, so in the task summary we can see which object that task is related to.

**Comment by rushthomas** [comment]
My personal hope is that the UX improvements include batch editing objects. That will be a huge win for usability.

**Comment by SamBouwer** [comment]
> My personal hope is that the UX improvements include batch editing objects. That will be a huge win for usability. 

Checkout this recently merged feature branch, you're in for a treat!
 https://github.com/anyproto/anytype-ts/commit/69a0271434a351bcc18c77af906d94d0d28a9dad

(hint: it allows you to bulk edit relations)
