### ISSUE TITLE
Date as an Object

### ISSUE THREAD

**Issue by y0ur1kopf** [anytypeio/roadmap#54]
**High level:**
Introduce a new "Date" object type with a consistent layout across Anytype to ensure uniformity in date representation. Display all objects, mentions and relations (e.g. Due Date, Creation Date) linked to a specific date. Enable users to interact with date data in various contexts, including layouts, sets and relations. Provide support for relative dates.

**Related threads & Feature Requests:**
• [Make the Date object type customizable](https://community.anytype.io/t/make-the-date-object-type-customizable/18868)

**Comment by eagleram13** [comment]
Would this mean that we can us a trigger such as @ or + to add a date automatically? Such as Today, Tomorrow or pick a date.

**Comment by telmob** [comment]
notifications finally happening?

**Comment by sonsnix** [comment]
This plus notifications is for me the most crucial feature that is missing.

I want to be able to link notes to dates, so I can later look at a date and see the Backlinks to that date.

**Comment by robotflaqd** [comment]
Agree with having dynamic dates (today, tomorrow, next Wednesday, April 2, 2025) by using @. And please have the ability to use @/remind [dynamic date] to set a reminder; 9am (local time) as default unless a specific time is typed). Make time easy to type e.g. 427am = 4:27 AM. 

@/remind jan 12 1109pm = Reminder on January 12th, 2025 11:09 PM

**Comment by goosethedev** [comment]
Maybe this issue should be reopened since it doesn't implement the desired customization on the linked FR. Namely:

- Making the Date a customizable Type to add blocks into it (useful for daily notes or journaling).
- Being able to show Date objects in the Graph view.

**Comment by y0ur1kopf** [comment]
> Maybe this issue should be reopened since it doesn't implement the desired customization on the linked FR. Namely:
> 
> * Making the Date a customizable Type to add blocks into it (useful for daily notes or journaling).
> * Being able to show Date objects in the Graph view.

Hey, in our local approach to adding blocks into the data object means that we need to pre-install all possible dates on your machine and make them "real block-based objects". This is hardly possible and was never part of the plan. All the mentioned dates can be found in the graph view.

**Comment by goosethedev** [comment]
> Hey, in our local approach to adding blocks into the data object means that we need to pre-install all possible dates on your machine and make them "real block-based objects". This is hardly possible and was never part of the plan.

Right now they seem to get created as view-only Sets when accessed, wouldn't it be possible to turn them into Pages when trying to edit them? (Maybe a separate issue would be better for that I guess).

> All the mentioned dates can be found in the graph view.

You're right. I got confused since only _mentioned_ dates are shown in the graph view. Setting a date relation isn't enough (e.g. when setting a due date on a task).
