### ISSUE TITLE
Simple counters (Stage 1)

### ISSUE THREAD

**Issue by geladariia** [anytypeio/roadmap#77]
**High level:**
Introduce simple counters for number relations, including Sum, Average, Median, Min, Max and Range. Additional counters, such as Count objects in Set or Collections, will be available for other field types. This feature aims to meet user requests for quick calculations without the complexity of full formulas.
Stage 1: Count objects in Set or Collections
Stage 2: Introduce simple counters for number relations, including Sum, Average, Median, Min, Max and Range.

**Related threads & Feature Requests:**
• ["Column" Aggregation in Sets (sum, average, etc.)](https://community.anytype.io/t/column-aggregation-in-sets-sum-average-etc/1557)

**Comment by Hardevv** [comment]
Would be great. I saw yesterday some pull request that probably delivers something like that for desktop. Does it mean it under development? When we can expect that?
